import { boot } from "@lumiarq/framework"
import { handleIgnitionError } from "@trazze/ignite"

/** Import bootstrap files — ensures bundler includes them for all targets */
import "./env"
import "./providers"

/**
 * Load all route files — fires Route.get/post/…() side-effects so the
 * registry is populated before boot() calls getRegisteredRoutes().
 * Generated by `lumis route:cache` (runs automatically before every build).
 */
import "@/storage/framework/cache/routes.loader"

/**
 * boot() sequence (framework-owned order):
 *   env.ts → providers.ts → applicationContext →
 *   discoverModules() → register per-module policies/listeners/schedule/routes →
 *   404 + error handlers → return LumiARQApp
 *
 * The adapter (selected at build time via Vite module aliasing) wraps LumiARQApp:
 *   --target node:       createNodeAdapter(app)       → HTTP server
 *   --target cloudflare: createCloudflareAdapter(app)  → { fetch: handler }
 *   --target static:     createStaticAdapter(app)      → prerender pipeline
 */

console.log(handleIgnitionError) // Ensure it's included in the bundle for all targets, even if not used in this file.
export default boot({
  onError: handleIgnitionError,
})

/**
 * Uncomment to hook into the boot sequence:
 */
// export default boot({
//   async beforeModuleLoad() {
//     // After providers, before module discovery
//   },
//   async afterBoot(app) {
//     // After all routes registered, before server accepts requests
//   },
// })
