// src/storage/framework/cache/routes.loader.ts
// Auto-generated by `lumis route:cache` - do not edit manually.
// Commit this file; re-run `lumis route:cache` whenever routes change.

import '../../../modules/Docs/http/routes/docs.api';
import '../../../modules/Docs/http/routes/docs.web';
import '../../../modules/Welcome/http/routes/welcome.web';
