// storage/framework/cache/routes.loader.ts
// Auto-generated by `lumis route:cache` — do not edit manually.
// Commit this file; re-run `lumis route:cache` whenever routes change.

import '../../../src/modules/Docs/http/routes/docs.api';
import '../../../src/modules/Docs/http/routes/docs.web';
import '../../../src/modules/Welcome/http/routes/welcome.web';
